# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Aarón Cruz
title: Computer Engineering
email: aaron.cruzgallegos@gmail.com
website: aaroncruz404.github.io/resume/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  aaroncruz404
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ramses-cruz-90289427b
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Computer Engineer with knowledge in C, C++, C# and Python programming languages, as well as familiarity with TypeScript and the React library. Knowledgeable in MySQL and PostgreSQL databases. Proactive approach to learning new technologies and constantly improving both soft and technical skills.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Website for transcribing audio to text
        link: https://github.com/aaroncruz404/transcripciones-web
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is an academic project to obtain my graduate certificate.
        description: | # this will include new lines to allow paragraphs
          The website transcribes audio to text and uses a technology stack that includes Astro, Flask, Python, React, Socket.io, Supabase, TypeScript, and WhisperIA. Working on this project has allowed me to develop skills in these technologies, and I’m proud to include it in my portfolio.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Social Service
        link: https://www.cucei.udg.mx/
        # link_text: boringcompany.com
        sub_title: Sysadmin Intern
        caption: September 2023 - February 2024
        quote: >
          I chose the servers area for my social service because I enjoy working with tangible technology. Unlike programming, where you mainly see results on a screen
        description: | # this will include new lines to allow paragraphs
            I have taken on responsibilities such as installing operating systems, configuring networks, managing user accounts, and implementing services like Apache, FTP, SSH, and MariaDB. Additionally, I have assisted in deploying academic websites. This project has allowed me to develop valuable skills in using Linux.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Guadalajara
        caption: 2020 - 2024
        sub_title: Computer Engineering
        quote: >
          The University Center of Exact Sciences and Engineering (CUCEI) is one of the thematic centers that form the University Network of Jalisco, currently serving more than 15,000 students through 18 undergraduate programs and 20 postgraduate programs.
        description: | # this will include new lines to allow paragraphs
          During my time at CUCEI I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Fronton
      - Gaming
      - Football
      - Martial Arts


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
